apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: oda
  janus-idp.io/tekton: oda
  backstage.io/kubernetes-id: oda
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: oda
resources:
  - application-dev.yaml
